version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: 'juma-mysql'
    env_file:
      - .env
    volumes:
      - mysqldata:/var/lib/mysql
      - ./my.conf:/etc/mysql/my.cnf
    ports:
      - "3333:3306"
  redis:
    image: redis
    container_name: juma-redis
    ports:
      - "6379:6379"
volumes:
  mysqldata:
