version: '3'
services:
  backend:
    container_name: juma-backend
    build:
      context: .
    depends_on:
      - mysql
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "4000:5000"
    networks:
      - juma-network
  mysql:
    networks:
      - juma-network
    image: mariadb
    container_name: 'juma-mysql'
    env_file:
      - .env
    volumes:
      - juma-data:/var/lib/mysql
      - ./my.conf:/etc/mysql/my.cnf
    ports:
      - "3333:3306"
  redis:
    image: redis
    container_name: juma-redis
    ports:
      - "6379:6379"
volumes:
  juma-data:

networks:
  juma-network:
